version: "3"

services:
  server:
    build: .
    command: npm run dev
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ~/Documents/hw1-se-school_2022-code-review-mykolastepanenko:/genesis-test
  rabbitmq:
    container_name: "RabbitMQ"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
